[[redirects]]
  from = "/index.html"
  to = "/"
  status = 301

[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap-index.xml"
  status = 301

[[redirects]]
  from = "/ads-privacy"
  to = "https://ads.angus.dev"
  status = 301

[[headers]]
  for = "/_astro/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
